
import { GoogleGenAI } from "@google/genai";
import { GeneratorConfig, ModelType, CameraAngle } from "../types";

export const generateMockup = async (config: GeneratorConfig): Promise<{ imageUrl: string; text?: string }> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key is missing");

  const ai = new GoogleGenAI({ apiKey });
  
  // Enhance prompt with camera angle instruction
  const cameraInstructions: Record<CameraAngle, string> = {
    [CameraAngle.EYE_LEVEL]: "Captured at a natural eye-level perspective",
    [CameraAngle.TOP_DOWN]: "A professional flat-lay top-down perspective",
    [CameraAngle.LOW_ANGLE]: "A dramatic low-angle perspective looking upwards",
    [CameraAngle.HIGH_ANGLE]: "An aerial high-angle perspective looking down",
    [CameraAngle.MACRO]: "An extreme macro close-up focusing on fine details and textures",
    [CameraAngle.ISOMETRIC]: "A stylized isometric 3D perspective"
  };

  const enhancedPrompt = `${cameraInstructions[config.cameraAngle]}. ${config.prompt}`;
  
  const contents: any = {
    parts: []
  };

  if (config.sourceImage) {
    contents.parts.push({
      inlineData: {
        data: config.sourceImage.split(',')[1],
        mimeType: 'image/png'
      }
    });

    // Reversed Logic: creativeMode true means Creative Mapping, false means Strict Preservation
    const preservationMode = config.creativeMode 
      ? `CREATIVE MAPPING MODE: Use the uploaded image as a thematic reference for the design style, colors, and layout, but allow the AI to blend it naturally and creatively into the new scene. Transform it to fit the mockup aesthetics.`
      : `STRICT PRESERVATION MODE: Treat the uploaded image as the EXACT graphic/cover. Preserve every detail, color, and font perfectly. Map it onto the object surface with 100% fidelity without changing the art.`;

    contents.parts.push({
      text: `ACT AS A PROFESSIONAL MOCKUP ENGINE. 
      ${preservationMode}
      SCENE CONTEXT: Place this design onto the main object in this scene: ${enhancedPrompt}. 
      Ensure realistic lighting, perspective, and surface integration.`
    });
  } else {
    contents.parts.push({
      text: enhancedPrompt
    });
  }

  const generationConfig: any = {
    imageConfig: {
      aspectRatio: config.aspectRatio,
    }
  };

  const response = await ai.models.generateContent({
    model: ModelType.FLASH,
    contents,
    config: generationConfig,
  });

  let imageUrl = '';
  let textOutput = '';

  if (response.candidates && response.candidates[0].content.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        imageUrl = `data:image/png;base64,${part.inlineData.data}`;
      } else if (part.text) {
        textOutput += part.text;
      }
    }
  }

  if (!imageUrl) {
    throw new Error("No image was generated by the model.");
  }

  return { imageUrl, text: textOutput };
};

export const checkProKey = async (): Promise<boolean> => {
  return true; 
};

export const openProKeySelector = async (): Promise<void> => {
};
